# Use an official Go runtime as a parent image
FROM golang:1.23 as builder

# Set the working directory
WORKDIR /app

# Copy the go.mod and go.sum files
COPY go.mod go.sum ./

# Download and cache the dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go app
RUN go build -o main ./cmd/.

# Start a new container from a minimal base
FROM gcr.io/distroless/base

# Copy the binary from the builder
COPY --from=builder /app/main /main

# Expose port 50052
EXPOSE 50052

# Command to run the executable
CMD ["/main"]
